add_subdirectory(example-bmark)
add_subdirectory(example-bmark-timed)
add_subdirectory(bandwidth-bmarks)
add_subdirectory(bmark-lib)
add_subdirectory(saturn-pvirus)
add_subdirectory(conv-pvirus)
add_subdirectory(conv-bmarks)
add_subdirectory(borai-int8-bmarks)
add_subdirectory(saturn-bmarks-shmoo)
add_subdirectory(audio-bmark)
add_subdirectory(app-fft-bmark)
